### PR TITLE
audio-worklet SSG bundling

### PR DESCRIPTION
**Pull request by neonfuz**
Moved the bundling of the audio worklet out of package.json scripts into a server route. Testing if this works on netlify. It should work even on static hosts due to enabling prerendering.

### CODE REVIEW

**Comment by neonfuz** [comment]
Hmm, I fixed the deploy preview build, and you can access the built worklet at /audio-worklet.js, but the synth is broken

**Comment by neonfuz** [comment]
Probably broke something updating all packages to latest. I'll revert that and update just what's necessary

**Comment by neonfuz** [comment]
It was actually because I disabled the client side router I guess. Re-enabled it, everything working.

**Comment by neonfuz** [comment]
Alright i just wanted to simplify & clarify history a bit. Should be ready for merge now. @44100hertz

**Comment by 44100hertz** [comment]
Ok cool. I will test on my machine and then merge

**Review by 44100hertz — APPROVED** [review]

**Comment by 44100hertz** [comment]
Works on my machine

**Pull request merged**
